# Generated by Django 4.1 on 2022-09-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saddmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytype',
            name='pro_img',
            field=models.ImageField(blank=True, null=True, upload_to='propertyimage/'),
        ),
    ]
