# Generated by Django 4.1 on 2022-09-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saddmin', '0002_propertytype_pro_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytype',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='baths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='overview',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='room',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='squer_fit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='pro_img',
            field=models.ImageField(blank=True, null=True, upload_to='propertyimage'),
        ),
    ]
