# Generated by Django 4.1 on 2022-09-07 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saddmin', '0004_country_cityname_state_statename_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='country',
            new_name='name',
        ),
    ]
