# Generated by Django 4.1 on 2022-09-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saddmin', '0005_rename_country_country_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytype',
            name='create_by',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
