# Generated by Django 4.1 on 2022-09-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saddmin', '0009_cityname_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='postequiry',
            name='create_by',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
