# Generated by Django 4.1 on 2022-09-14 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saddmin', '0010_postequiry_create_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cityname',
            old_name='country',
            new_name='country_id',
        ),
        migrations.RenameField(
            model_name='cityname',
            old_name='state',
            new_name='state_id',
        ),
    ]
