# Generated by Django 4.1 on 2022-09-14 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saddmin', '0012_propertytype_city_propertytype_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytype',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saddmin.statename'),
        ),
    ]
